// sku code map
export default {
    Network: {
        'NA': 'A0',
        'Search': 'A1',
        'Display': 'A2',
        'Social': 'A3',
        'Email': 'A4',
        'Ad_Video': 'A5'
    },
    TargetingMethod: {
        'NA': 'B0',
        'KWD': 'B1',
        'MP': 'B2',
        'MP-KWD': 'B3',
        'Topic': 'B4',
        'Topic-KWD': 'B5',
        'Connection': 'B6',
        'Behavior': 'B7',
        'Demographic': 'B8',
        'Interest': 'B9',
        'Lookalike': 'B10',
        'Remarketing': 'B11',
        'Newsletter - About': 'B12',
        'Newsletter - Programs': 'B13',
        'Newsletter - Addiction': 'B14',
        'Newsletter - PTSD': 'B15',
        'Newsletter - MH': 'B16',
        'Run of Site': 'B17',
        'Geographic': 'B18',
        'Conversion': 'B19',
        'Newsletter - Mood': 'B20',
        'No Response - SF': 'B21',
        'Custom Segments': 'B22',
        'Dynamic - Domain': 'B23',
        'Dynamic - SSE': 'B24',
        'Question': 'B25',
        'Question Retargeting': 'B26',
        'Sign-Up': 'B27',
        'Eblast': 'B28',
        'No Response': 'B29',
        'Smart Display': 'B30',
    },
    Format: {
        'NA': 'C0',
        'Canvas Ad': 'C1',
        '2 Headline': 'C2',
        'GIF': 'C3',
        'Gmail Ad': 'C4',
        'HTML': 'C5',
        'Image Carousel': 'C6',
        'Lightbox': 'C7',
        'Link Post': 'C8',
        'Photo Post': 'C9',
        'Responsive': 'C10',
        'Static Image': 'C11',
        'Video': 'C12',
        'Video Carousel': 'C13',
        'Long Content - No Image': 'C14',
        'Long Content - Image': 'C15',
        'Short Content - No Image': 'C16',
        'Short Content - Image': 'C17',
        'Banner': 'C18',
        'Profile': 'C19',
        'Text Ad': 'C20',
        '3 Headline': 'C21',
        'Dynamic Headline': 'C22',
        'Native': 'C23',
        'Email 1': 'C24',
        'Email 2': 'C25',
        'Email 3': 'C26',
    },
    Message: {
        'NA': 'D0',
        'About-General': 'D1',
        'About-Other': 'D2',
        'About-Self': 'D3',
        'Benefits-General': 'D4',
        'Benefits-Other': 'D5',
        'Benefits-Self': 'D6',
        'Emotion-General': 'D7',
        'Emotion-Other': 'D8',
        'Emotion-Self': 'D9',
        'Leading-General': 'D10',
        'Leading-Other': 'D11',
        'Leading-Self': 'D12',
        'Scare-General': 'D13',
        'Scare-Other': 'D14',
        'Scare-Self': 'D15',
        'Stats-General': 'D16',
        'Stats-Other': 'D17',
        'Stats-Self': 'D18',
        'Urgent-General': 'D19',
        'Urgent-Other': 'D20',
        'Urgent-Self': 'D21',
        'Dynamic Message': 'D22',
        'Info-General': 'D23',
        'Info-Other': 'D24',
        'Info-Self': 'D25',
        'Question-General': 'D26',
        'Question-Other': 'D27',
        'Question - Self': 'D28',
        'Hope - General': 'D29',
        'Hope - Other': 'D30',
        'Hope - Self': 'D31',
        // 'Email - About Button': 'D32',
        // 'Email - Admissions Button': 'D33',
        // 'Email - Contact Button': 'D34',
        // 'Email - Disorders Button': 'D35',
        // 'Email - Programs Button': 'D36',
        // 'Email - Services Button': 'D37',
        // 'Email - Testimonials Button': 'D38',
        // 'Email - Tour Button': 'D39',
        // 'Email - Therapies Button': 'D40',
        // 'Email - Logo Header': 'D41',
    },
    AgeRange: {
        'NA': 'E0',
        '18-24': 'E1',
        '25-34': 'E2',
        '35-44': 'E3',
        '35-49': 'E4',
        '45-54': 'E5',
        '50-64': 'E6',
        '55-64': 'E7',
        '65+': 'E8',
        'All': 'E9',
        'Undetermined': 'E10'
    },
    Ethnicity: {
        'NA': 'F0',
        'African American': 'F1',
        'Asian': 'F2',
        'Hispanic': 'F3',
        'Native American': 'F4',
        'Pacific Islander': 'F5',
        'Two or More Races': 'F6',
        'White': 'F7',
        'Undetermined': 'F8',
        'All': 'F9'
    },
    FamilyRole: {
        'NA': 'G0',
        'Brother': 'G1',
        'Daughter': 'G2',
        'Husband': 'G3',
        'Parent - Expecting': 'G4',
        'Parent - 0-12 Month': 'G5',
        'Parent - Pre-Teen': 'G6',
        'Parent - Teen': 'G7',
        'Parent - Adult Child': 'G8',
        'Sister': 'G9',
        'Son': 'G10',
        'Wife': 'G11',
        'Undetermined': 'G12',
        'All': 'G13',
        'Parent': 'G14',
        'Email - Self': 'G15',
        'Email - Someone Else': 'G16',
    },
    Gender: {
        'NA': 'H0',
        'Female': 'H1',
        'Male': 'H2',
        'Undetermined': 'H3',
        'All': 'H4'
    },
    Income: {
        'NA': 'I0',
        '39k or Less': 'I1',
        '40k-49k': 'I2',
        '50k-74k': 'I3',
        '75k-99k': 'I4',
        '100k-124k': 'I5',
        '125k-149k': 'I6',
        '150k-249k': 'I7',
        '250k-349k': 'I8',
        '350k-499k': 'I9',
        '500k or More': 'I10',
        'Undetermined': 'I11',
        'All': 'I12'
    },
    InterestsBehaviors: {
        'NA': 'J0',
        'Away from Family': 'J1',
        'Away from Home': 'J2',
        'Business and Industry': 'J3',
        'Chronic Relapser': 'J4',
        'Democrat': 'J5',
        'Detox Seeker': 'J6',
        'Entertainment': 'J7',
        'Fitness and Wellness': 'J8',
        'Food and Drink': 'J9',
        'Friends of Alumni': 'J10',
        'LGBT Population': 'J11',
        'Outdoors': 'J12',
        'Politics': 'J13',
        'Previous Patient of Competitor': 'J14',
        'Republican': 'J15',
        'Shopping and Fashion': 'J16',
        'Sports': 'J17',
        'Technology': 'J18',
        'Travel': 'J19',
        'Undetermined': 'J20',
        'All': 'J21',
        'Employers': 'J22'
    },
    Language: {
        'NA': 'K0',
        'English': 'K1',
        'Spanish': 'K2',
        'Bilingual': 'K3',
        'Undetermined': 'K4',
        'All': 'K5'
    },
    Education: {
        'NA': 'L0',
        'Some High School': 'L1',
        'High School Grad': 'L2',
        'Associate Degree': 'L3',
        'Some College': 'L4',
        'College Grad': 'L5',
        'Professional Degree': 'L6',
        'Some Grad School': 'L7',
        "Master's Degree": 'L8',
        'Doctorate Degree': 'L9',
        'Undetermined': 'L10',
        'All': 'L11'
    },
    Occupation: {
        'NA': 'M0',
        'Admin': 'M1',
        'Arts': 'M2',
        'Business and Finance': 'M3',
        'Executive': 'M4',
        'Government': 'M5',
        'Healthcare': 'M6',
        'IT': 'M7',
        'Legal': 'M8',
        'Manufacturing': 'M9',
        'Sales': 'M10',
        'Service': 'M11',
        'Student-College': 'M12',
        'Student-Grad School': 'M13',
        'Student-High School': 'M14',
        'Unemployed': 'M15',
        'Undetermined': 'M16',
        'All': 'M17'
    },
    Relationship: {
        'NA': 'N0',
        'Divorced': 'N1',
        'Married': 'N2',
        'Separated': 'N3',
        'Single': 'N4',
        'Undetermined': 'N5',
        'All': 'N6'
    },
    Religion: {
        'NA': 'O0',
        'Agnosticism': 'O1',
        'Atheism': 'O2',
        'Buddhism': 'O3',
        'Christianity': 'O4',
        'Hindu': 'O5',
        'Islam': 'O6',
        'Judaism': 'O7',
        'Mormonism': 'O8',
        'Sikhism': 'O9',
        'Undetermined': 'O10',
        'All': 'O11'
    },
    InverseCodes: {
        "A0": "NA",
        "A1": "Search",
        "A2": "Display",
        "A3": "Social",
        "A4": "Email",
        "A5": "Ad_Video",
        "B0": "NA",
        "B1": "KWD",
        "B2": "MP",
        "B3": "MP-KWD",
        "B4": "Topic",
        "B5": "Topic-KWD",
        "B6": "Connection",
        "B7": "Behavior",
        "B8": "Demographic",
        "B9": "Interest",
        "B10": "Lookalike",
        "B11": "Remarketing",
        "B12": "Newsletter - About",
        "B13": "Newsletter - Programs",
        "B14": "Newsletter - Addiction",
        "B15": "Newsletter - PTSD",
        "B16": "Newsletter - MH",
        "B17": "Run of Site",
        "B18": "Geographic",
        "B19": "Conversion",
        "B20": "Newsletter - Mood",
        "B21": "No Response - SF",
        "B22": "Custom Segments",
        "B23": "Dynamic - Domain",
        "B24": "Dynamic - SSE",
        "B25": "Question",
        "B26": "Question Retargeting",
        "B27": "Sign-Up",
        "B28": "Eblast",
        "B29": "No Response",
        "B30": "Smart Display",
        "C0": "NA",
        "C1": "Canvas Ad",
        "C2": "2 Headline",
        "C3": "GIF",
        "C4": "Gmail Ad",
        "C5": "HTML",
        "C6": "Image Carousel",
        "C7": "Lightbox",
        "C8": "Link Post",
        "C9": "Photo Post",
        "C10": "Responsive",
        "C11": "Static Image",
        "C12": "Video",
        "C13": "Video Carousel",
        "C14": "Long Content - No Image",
        "C15": "Long Content - Image",
        "C16": "Short Content - No Image",
        "C17": "Short Content - Image",
        "C18": "Banner",
        "C19": "Profile",
        "C20": "Text Ad",
        "C21": "3 Headline",
        "C22": "Dynamic Headline",
        "C23": "Native",
        'C24': 'Email 1',
        'C25': 'Email 2',
        'C26': 'Email 3',
        "D0": "NA",
        "D1": "About-General",
        "D2": "About-Other",
        "D3": "About-Self",
        "D4": "Benefits-General",
        "D5": "Benefits-Other",
        "D6": "Benefits-Self",
        "D7": "Emotion-General",
        "D8": "Emotion-Other",
        "D9": "Emotion-Self",
        "D10": "Leading-General",
        "D11": "Leading-Other",
        "D12": "Leading-Self",
        "D13": "Scare-General",
        "D14": "Scare-Other",
        "D15": "Scare-Self",
        "D16": "Stats-General",
        "D17": "Stats-Other",
        "D18": "Stats-Self",
        "D19": "Urgent-General",
        "D20": "Urgent-Other",
        "D21": "Urgent-Self",
        "D22": "Dynamic Message",
        "D23": "Info-General",
        "D24": "Info-Other",
        "D25": "Info-Self",
        "D26": "Question-General",
        "D27": "Question-Other",
        "D28": "Question-Self",
        "D29": "Hope-General",
        "D30": "Hope-Other",
        "D31": "Hope-Self",
        // 'D32': 'Email - About Button',
        // 'D33': 'Email - Admissions Button',
        // 'D34': 'Email - Contact Button',
        // 'D35': 'Email - Disorders Button',
        // 'D36': 'Email - Programs Button',
        // 'D37': 'Email - Services Button',
        // 'D38': 'Email - Testimonials Button',
        // 'D39': 'Email - Tour Button',
        // 'D40': 'Email - Therapies Button',
        // 'D41': 'Email - Logo Header',
        "E0": "NA",
        "E1": "18-24",
        "E2": "25-34",
        "E3": "35-44",
        "E4": "35-49",
        "E5": "45-54",
        "E6": "50-64",
        "E7": "55-64",
        "E8": "65+",
        "E9": "All",
        "E10": "Undetermined",
        "F0": "NA",
        "F1": "African American",
        "F2": "Asian",
        "F3": "Hispanic",
        "F4": "Native American",
        "F5": "Pacific Islander",
        "F6": "Two or More Races",
        "F7": "White",
        "F8": "Undetermined",
        "F9": "All",
        "G0": "NA",
        "G1": "Brother",
        "G2": "Daughter",
        "G3": "Husband",
        "G4": "Parent - Expecting",
        "G5": "Parent - 0-12 Month",
        "G6": "Parent - Pre-Teen",
        "G7": "Parent - Teen",
        "G8": "Parent - Adult Child",
        "G9": "Sister",
        "G10": "Son",
        "G11": "Wife",
        "G12": "Undetermined",
        "G13": "All",
        "G14": "Parent",
        'G15': 'Email - Self',
        'G16': 'Email - Someone Else',
        "H0": "NA",
        "H1": "Female",
        "H2": "Male",
        "H3": "Undetermined",
        "H4": "All",
        "I0": "NA",
        "I1": "39k or Less",
        "I2": "40k-49k",
        "I3": "50k-74k",
        "I4": "75k-99k",
        "I5": "100k-124k",
        "I6": "125k-149k",
        "I7": "150k-249k",
        "I8": "250k-349k",
        "I9": "350k-499k",
        "I10": "500k or More",
        "I11": "Undetermined",
        "I12": "All",
        "J0": "NA",
        "J1": "Away from Family",
        "J2": "Away from Home",
        "J3": "Business and Industry",
        "J4": "Chronic Relapser",
        "J5": "Democrat",
        "J6": "Detox Seeker",
        "J7": "Entertainment",
        "J8": "Fitness and Wellness",
        "J9": "Food and Drink",
        "J10": "Friends of Alumni",
        "J11": "LGBT Population",
        "J12": "Outdoors",
        "J13": "Politics",
        "J14": "Previous Patient of Competitor",
        "J15": "Republican",
        "J16": "Shopping and Fashion",
        "J17": "Sports",
        "J18": "Technology",
        "J19": "Travel",
        "J20": "Undetermined",
        "J21": "All",
        "J22": "Employers",
        "K0": "NA",
        "K1": "English",
        "K2": "Spanish",
        "K3": "Bilingual",
        "K4": "Undetermined",
        "K5": "All",
        "L0": "NA",
        "L1": "Some High School",
        "L2": "High School Grad",
        "L3": "Associate Degree",
        "L4": "Some College",
        "L5": "College Grad",
        "L6": "Professional Degree",
        "L7": "Some Grad School",
        "L8": "Master's Degree",
        "L9": "Doctorate Degree",
        "L10": "Undetermined",
        "L11": "All",
        "M0": "NA",
        "M1": "Admin",
        "M2": "Arts",
        "M3": "Business and Finance",
        "M4": "Executive",
        "M5": "Government",
        "M6": "Healthcare",
        "M7": "IT",
        "M8": "Legal",
        "M9": "Manufacturing",
        "M10": "Sales",
        "M11": "Service",
        "M12": "Student-College",
        "M13": "Student-Grad School",
        "M14": "Student-High School",
        "M15": "Unemployed",
        "M16": "Undetermined",
        "M17": "All",
        "N0": "NA",
        "N1": "Divorced",
        "N2": "Married",
        "N3": "Separated",
        "N4": "Single",
        "N5": "Undetermined",
        "N6": "All",
        "O0": "NA",
        "O1": "Agnosticism",
        "O2": "Atheism",
        "O3": "Buddhism",
        "O4": "Christianity",
        "O5": "Hindu",
        "O6": "Islam",
        "O7": "Judaism",
        "O8": "Mormonism",
        "O9": "Sikhism",
        "O10": "Undetermined",
        "O11": "All"
    }
}
